/**
 * Provenance stamp for artifacts this server writes.
 *
 * Someone inheriting a WordPress site should be able to tell which plugins and
 * themes an AI wrote without asking anyone. Two marks, because they survive
 * different things:
 *
 * - Header lines in the file WordPress always parses (a plugin's main PHP file,
 *   a theme's style.css). WordPress ignores headers it does not know, so this is
 *   free, and it travels with the directory when it is copied to another site.
 * - A suffix on `Description`, which is the only one of the two a human sees
 *   without tooling — it renders in wp-admin → Plugins / Appearance → Themes.
 *
 * This is provenance, not attestation. It records what rolepod-wplab wrote; it
 * cannot prove an unmarked plugin was hand-written, and anyone may delete the
 * lines. The server-side change ledger is the counterpart that a file edit
 * cannot rewrite — see `rolepod_wp_changes_query`.
 *
 * @packageDocumentation
 */

/** Header key carrying the tool identity. Grep target, and machine-readable. */
export const PROVENANCE_HEADER_KEY = "Generated-By";

/** Header key carrying the UTC date. Separate key so the value stays parseable. */
export const PROVENANCE_DATE_KEY = "Generated-At";

/** Value of {@link PROVENANCE_HEADER_KEY}. Kept literal so a grep is exact. */
export const PROVENANCE_AGENT = "rolepod-wplab";

/** Appended to `Description` so the mark is visible with no tooling at all. */
export const PROVENANCE_DESCRIPTION_SUFFIX = `(generated by ${PROVENANCE_AGENT})`;

function today(now?: Date): string {
  return (now ?? new Date()).toISOString().slice(0, 10);
}

/**
 * The two header lines, without comment punctuation.
 *
 * @param version - server version, e.g. "3.3.1". Omitted when unknown rather
 *                  than guessed, so the value never lies about which build ran.
 */
export function provenanceHeaderLines(version?: string, now?: Date): string[] {
  const agent = version ? `${PROVENANCE_AGENT} ${version}` : PROVENANCE_AGENT;

  return [
    `${PROVENANCE_HEADER_KEY}: ${agent}`,
    `${PROVENANCE_DATE_KEY}: ${today(now)}`,
  ];
}

/** Header lines for a PHP docblock (` * Key: value`). */
export function provenancePhpHeader(version?: string, now?: Date): string {
  return provenanceHeaderLines(version, now)
    .map((l) => ` * ${l}`)
    .join("\n");
}

/** Header lines for a theme `style.css` block (`Key: value`). */
export function provenanceCssHeader(version?: string, now?: Date): string {
  return provenanceHeaderLines(version, now).join("\n");
}

/**
 * Append the visible suffix to a description, once.
 *
 * Idempotent: re-scaffolding over an already-marked description must not stack
 * the suffix, and a description that arrives already carrying it is left alone.
 */
export function withProvenanceSuffix(description: string): string {
  const trimmed = description.trim();
  if (trimmed.includes(PROVENANCE_DESCRIPTION_SUFFIX)) {
    return trimmed;
  }
  if (trimmed === "") {
    return PROVENANCE_DESCRIPTION_SUFFIX;
  }

  return `${trimmed} ${PROVENANCE_DESCRIPTION_SUFFIX}`;
}

/**
 * Does a file's head carry the stamp? Reads the raw first bytes of a plugin's
 * main PHP file or a theme's style.css — no PHP execution needed.
 */
export function hasProvenanceStamp(head: string): boolean {
  return new RegExp(
    `^\\s*\\*?\\s*${PROVENANCE_HEADER_KEY}:\\s*${PROVENANCE_AGENT}\\b`,
    "im",
  ).test(head);
}
