import { describe, expect, it } from "vitest";
import {
  PROVENANCE_AGENT,
  PROVENANCE_DESCRIPTION_SUFFIX,
  hasProvenanceStamp,
  provenanceCssHeader,
  provenancePhpHeader,
  withProvenanceSuffix,
} from "../../src/lib/provenance.js";

const AT = new Date("2026-09-04T12:00:00Z");

describe("provenance stamp", () => {
  it("emits a PHP docblock header a grep can find", () => {
    const php = provenancePhpHeader(undefined, AT);

    expect(php).toBe(
      ` * Generated-By: ${PROVENANCE_AGENT}\n * Generated-At: 2026-09-04`,
    );
    expect(hasProvenanceStamp(php)).toBe(true);
  });

  it("emits a style.css header without the docblock punctuation", () => {
    const css = provenanceCssHeader(undefined, AT);

    expect(css).toBe(
      `Generated-By: ${PROVENANCE_AGENT}\nGenerated-At: 2026-09-04`,
    );
    expect(hasProvenanceStamp(css)).toBe(true);
  });

  it("includes the version only when one is known", () => {
    expect(provenancePhpHeader("3.4.0", AT)).toContain(
      `Generated-By: ${PROVENANCE_AGENT} 3.4.0`,
    );
    // No version is better than a wrong one — never invent a number.
    expect(provenancePhpHeader(undefined, AT)).toContain(
      `Generated-By: ${PROVENANCE_AGENT}\n`,
    );
  });

  it("appends the visible suffix to a description", () => {
    expect(withProvenanceSuffix("A contact form")).toBe(
      `A contact form ${PROVENANCE_DESCRIPTION_SUFFIX}`,
    );
  });

  it("does not stack the suffix when re-scaffolding", () => {
    const once = withProvenanceSuffix("A contact form");

    expect(withProvenanceSuffix(once)).toBe(once);
    expect(once.match(/generated by/g)).toHaveLength(1);
  });

  it("handles an empty description without a leading space", () => {
    expect(withProvenanceSuffix("")).toBe(PROVENANCE_DESCRIPTION_SUFFIX);
    expect(withProvenanceSuffix("   ")).toBe(PROVENANCE_DESCRIPTION_SUFFIX);
  });

  it("detects the stamp in a real plugin header", () => {
    const head = `<?php
/**
 * Plugin Name: Example
 * Description: Does a thing ${PROVENANCE_DESCRIPTION_SUFFIX}
 * Version: 0.1.0
 * Author: Someone
${provenancePhpHeader(undefined, AT)}
 * License: GPL-2.0-or-later
 */`;

    expect(hasProvenanceStamp(head)).toBe(true);
  });

  it("detects the stamp in a theme style.css header", () => {
    const head = `/*
Theme Name: Example
Description: A theme ${PROVENANCE_DESCRIPTION_SUFFIX}
Version: 0.1.0
${provenanceCssHeader(undefined, AT)}
*/`;

    expect(hasProvenanceStamp(head)).toBe(true);
  });

  it("does not claim a stamp on an unmarked plugin", () => {
    const head = `<?php
/**
 * Plugin Name: Hand written
 * Description: Someone typed this
 * Version: 1.0.0
 */`;

    expect(hasProvenanceStamp(head)).toBe(false);
  });

  it("does not match the agent name appearing in prose", () => {
    // A readme that merely mentions the tool is not a provenance claim.
    const head = `<?php
/**
 * Plugin Name: Notes
 * Description: Compatible with ${PROVENANCE_AGENT} and other tools.
 */`;

    expect(hasProvenanceStamp(head)).toBe(false);
  });
});
