/**
 * Tools with no citation in `skills/` or `README.md`.
 *
 * SHRINK-ONLY. The drift gate fails if a tool here becomes documented and is
 * not removed from this list, and fails if a new tool ships undocumented and
 * is not added. Delete entries as the skills grow; never add one to silence
 * the gate for a tool you just wrote.
 */
export const UNDOCUMENTED_TOOLS: readonly string[] = [
  "rolepod_wp_admin_one_time_link",
  "rolepod_wp_cf7_form_create",
  "rolepod_wp_conventions_get",
  "rolepod_wp_conventions_set",
  "rolepod_wp_custom_init",
  "rolepod_wp_custom_task_list",
  "rolepod_wp_custom_task_remove",
  "rolepod_wp_custom_task_scaffold",
  "rolepod_wp_custom_task_toggle",
  "rolepod_wp_custom_task_update",
  "rolepod_wp_dir_ensure",
  "rolepod_wp_elementor_restore",
  "rolepod_wp_elementor_section",
  "rolepod_wp_file_copy",
  "rolepod_wp_file_disable",
  "rolepod_wp_file_enable",
  "rolepod_wp_file_list",
  "rolepod_wp_file_read",
  "rolepod_wp_file_write_batch",
  "rolepod_wp_global_styles_set",
  "rolepod_wp_jetengine_read",
  "rolepod_wp_jetengine_write",
  "rolepod_wp_job_create",
  "rolepod_wp_job_status",
  "rolepod_wp_media_optimize",
  "rolepod_wp_memory_list",
  "rolepod_wp_memory_note",
  "rolepod_wp_memory_recall",
  "rolepod_wp_menu_add_item",
  "rolepod_wp_menu_assign",
  "rolepod_wp_menu_create",
  "rolepod_wp_metabox_read",
  "rolepod_wp_metabox_write",
  "rolepod_wp_pods_read",
  "rolepod_wp_pods_write",
  "rolepod_wp_product_create",
  "rolepod_wp_recovery_disable_file",
  "rolepod_wp_recovery_disable_plugin",
  "rolepod_wp_recovery_list_changes",
  "rolepod_wp_recovery_restore_file",
  "rolepod_wp_recovery_restore_snapshot",
  "rolepod_wp_recovery_safe_mode",
  "rolepod_wp_recovery_status",
  "rolepod_wp_render_get",
  "rolepod_wp_seo_set",
  "rolepod_wp_set_front_page",
  "rolepod_wp_site_backup",
  "rolepod_wp_site_restore",
  "rolepod_wp_site_scaffold",
  "rolepod_wp_skill_catalog",
  "rolepod_wp_skill_delete",
  "rolepod_wp_skill_edit",
  "rolepod_wp_skill_get",
  "rolepod_wp_skill_write",
  "rolepod_wp_target_alias",
];
